#!/usr/bin/env node

import { cyan, dim, green, red, yellow } from '../../Terminal/index.ts';
import { get_repo_root } from '../../Workspace/index.ts';

import { spawnSync } from 'child_process';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

function run(): number {
    let repoRoot;
    try {
        repoRoot = get_repo_root();
    } catch (_e: unknown) {

        console.error(red('Error: Not inside a git repository.'));
        return 1;
    }

    console.log(cyan(`\nOrchestrating Automated Release...\n`));

    // Get the last tag
    const tagRes = spawnSync('git', ['describe', '--tags', '--abbrev=0'], { cwd: repoRoot, encoding: 'utf8' });
    const lastTag = tagRes.status === 0 ? tagRes.stdout.trim() : null;

    const logArgs = ['log', '--pretty=format:%h - %s'];
    if (lastTag) {
        console.log(dim(`Found previous tag: ${lastTag}`));
        logArgs.push(`${lastTag}..HEAD`);
    } else {
        console.log(dim(`No previous tags found. Generating from beginning of history.`));
    }

    const logRes = spawnSync('git', logArgs, { cwd: repoRoot, encoding: 'utf8' });
    if (logRes.status !== 0) {
        console.error(red(`Failed to read git log.`));
        return 1;
    }

    const commits = logRes.stdout.trim().split('\n').filter(Boolean);
    if (commits.length === 0) {
        console.log(yellow(`No new commits since ${String(lastTag)}. Nothing to release.`));
        return 0;
    }

    console.log(green(`✓ Analyzed ${String(commits.length)} commits.`));

    const releaseDir = join(repoRoot, '.agents', 'releases');
    if (!existsSync(releaseDir)) mkdirSync(releaseDir, { recursive: true });

    // Determine version bump heuristically
    let bump = 'patch';
    if (commits.some((c) => c.toLowerCase().includes('breaking') || c.toLowerCase().includes('major'))) {
        bump = 'major';
    } else if (commits.some((c) => c.toLowerCase().includes('feat:') || c.toLowerCase().includes('feature'))) {
        bump = 'minor';
    }

    // Calculate the new version
    const currentVer = lastTag ? lastTag.replace(/^v/, '') : '0.0.0';
    const match = /^(\d+)\.(\d+)\.(\d+)/.exec(currentVer);
    let major = 0;
    let minor = 0;
    let patch = 0;
    if (match) {
        major = parseInt(match[1], 10);
        minor = parseInt(match[2], 10);
        patch = parseInt(match[3], 10);
    }
    if (bump === 'major') {
        major++;
        minor = 0;
        patch = 0;
    } else if (bump === 'minor') {
        minor++;
        patch = 0;
    } else {
        patch++;
    }
    const nextVer = `v${major.toString()}.${minor.toString()}.${patch.toString()}`;

    const releaseNotes = `# Release Notes: ${nextVer}

## Summary
Auto-generated release based on ${String(commits.length)} commits since ${lastTag ?? 'initial commit'}.
Type of bump: **${bump.toUpperCase()}**

## Changelog

${commits.map((c) => `- ${c}`).join('\n')}

---
*Generated by Swarm Evolution V5 Release Orchestrator*
`;

    const notePath = join(releaseDir, `release-${nextVer}.md`);
    writeFileSync(notePath, releaseNotes, 'utf8');

    console.log(green(`\n✓ Release drafted: `) + dim(notePath));
    console.log(yellow(`\nReview the draft notes. If approved, run:`));
    console.log(dim(`git tag ${nextVer}`));
    console.log(dim(`git push origin ${nextVer}`));
    console.log('');
    return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
    process.exitCode = run();
}
